In [ ]:
!pip install yfinance

In [ ]:
# The aim of this program is to predict stock prices by using ML
import yfinance
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [ ]:
# Yfinance or Yahoo finance is an API for all the financial/economical datas (historical prices, interest rate, index, inflation rate, unemployment rate..)
# Numpy as Numerical Python is for all the calculations
# Scikit-learn as sklearn is a library for ML we are going to use the linear regression for the stock prediction -> This model is used to predict continuous numerical values

In [ ]:
import yfinance as yf

In [ ]:
# Get the stock data with the DT Wiki

In [ ]:
dataframe = yf.download('BN.PA')
dataframe.tail()

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close  Adj Close   Volume
Date                                                                      
2024-09-16  64.940002  65.699997  64.919998  65.300003  65.300003  1070672
2024-09-17  65.540001  65.599998  64.400002  64.699997  64.699997  1667007
2024-09-18  64.620003  65.040001  64.379997  64.519997  64.519997   881046
2024-09-19  64.980003  65.019997  64.360001  64.639999  64.639999  1216405
2024-09-20  64.820000  65.000000  64.440002  64.459999  64.459999  2308428

In [ ]:
# tail = last lines VS head = first lines

In [ ]:
# Get the adjusted close price (independent variable)

In [ ]:
dataframe = dataframe[['Adj Close']]
dataframe.tail()

Adj Close
Date                 
2024-09-16  65.300003
2024-09-17  64.699997
2024-09-18  64.519997
2024-09-19  64.639999
2024-09-20  64.459999

In [ ]:
# Create a variable to predict (number is the day)

In [ ]:
forecast_out = 5

In [ ]:
# Create another column (the target or dependent variable) shifted 'n' units up

In [ ]:
dataframe['Prediction'] = dataframe[['Adj Close']].shift(-forecast_out)
dataframe.tail()

<ipython-input-229-69d040cde381>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['Prediction'] = dataframe[['Adj Close']].shift(-forecast_out)


Adj Close  Prediction
Date                             
2024-09-16  65.300003         NaN
2024-09-17  64.699997         NaN
2024-09-18  64.519997         NaN
2024-09-19  64.639999         NaN
2024-09-20  64.459999         NaN

In [ ]:
# NaN is Not a number for missing value

In [ ]:
# We need to create the independent data set (X)
# With convert the dataframe to a numpy array

X = np.array(dataframe.drop(['Prediction'], axis=1))

# Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[[ 1.99056602]
 [ 1.99056602]
 [ 1.99056602]
 ...
 [65.77999878]
 [65.37999725]
 [65.08000183]]


In [ ]:
## create the dependent data set (y)
## Convert the dataframe to a numpy array (all of the values including the NaN's)
#
y = np.array(dataframe['Prediction'])

# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print(y)
#

[ 1.90418041  1.90418041  1.90418041 ... 64.51999664 64.63999939
 64.45999908]


In [ ]:
# Split the data into 80% training and 20% testing

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# create and train the Support Vector Machine (regressor)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, gamma=0.1)

In [ ]:
# testing model : score returns the coefficient of determination R^2 of the prediction
# The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print('svm confidence: ', svm_confidence)
#

svm confidence:  0.9977673663672613


In [ ]:
# Create and train the linear regression model

lr = LinearRegression()

# Train the model

lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
## testing model : score returns the coefficient of determination R^2 of the prediction
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print('lr confidence: ', lr_confidence)
#

lr confidence:  0.9977366098560105


In [ ]:
# set x_forecast equal to the last 30 rows of the original data set from Adj Close column

x_forecast = np.array(dataframe.drop(['Prediction'], axis=1))[-forecast_out:]
print(x_forecast)

[[65.30000305]
 [64.69999695]
 [64.51999664]
 [64.63999939]
 [64.45999908]]


In [ ]:
# Print the predictions for the next 'n' days

lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

# Print support vector regressor model predictions for the next 'n' days

svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[65.28397122 64.68455936 64.50473732 64.62462122 64.44479918]
[66.27668311 66.0071199  65.77327875 65.93698303 65.68033587]
